<a href="https://colab.research.google.com/github/shubh28012004/data_cleaning/blob/main/DPL_4_Data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**General types of data :-**


*   Quantitative (numerical) - Discrete and continous
*   Qualitative (categorical) - ordinal and norminal

**Missing data handling options :-**
* Keeping the data as it is
* removing that particular data
* replacing the data with dummy data (imputation)

* you should be knowing input and output variable very well
* you should be aware of the size of the data set .

In [43]:
import pandas as pd
import numpy as np

In [44]:
df = pd.read_excel("/content/Data Cleaning_part1_dataset_movie scores.xlsx")

In [45]:
df

  first_name last_name   age Gender  pre_movie_score  post_movie_score
0       Root      Joss  36.0      m              8.0               9.0
1        NaN       NaN   NaN    NaN              NaN               NaN
2      Stark      Mike  48.0      m              NaN               NaN
3      Sofie    Miller  39.0      f              7.0               8.0
4       Emma       Roy  84.0      f              6.0               8.0

**To find null values**

In [46]:
df.isnull()

   first_name  last_name    age  Gender  pre_movie_score  post_movie_score
0       False      False  False   False            False             False
1        True       True   True    True             True              True
2       False      False  False   False             True              True
3       False      False  False   False            False             False
4       False      False  False   False            False             False

In [47]:
df.notnull() # which are not null gives true if not than false

   first_name  last_name    age  Gender  pre_movie_score  post_movie_score
0        True       True   True    True             True              True
1       False      False  False   False            False             False
2        True       True   True    True            False             False
3        True       True   True    True             True              True
4        True       True   True    True             True              True

In [48]:
df['first_name'] # finding out null values in specific columns

0     Root
1      NaN
2    Stark
3    Sofie
4     Emma
Name: first_name, dtype: object

In [49]:
df[df['first_name'].notnull()]

  first_name last_name   age Gender  pre_movie_score  post_movie_score
0       Root      Joss  36.0      m              8.0               9.0
2      Stark      Mike  48.0      m              NaN               NaN
3      Sofie    Miller  39.0      f              7.0               8.0
4       Emma       Roy  84.0      f              6.0               8.0

In [50]:
df[df['first_name'].isnull()]

  first_name last_name  age Gender  pre_movie_score  post_movie_score
1        NaN       NaN  NaN    NaN              NaN               NaN

**non null and null values form multiple row or column**

In [51]:
df[(df['pre_movie_score'].isnull()) & df['Gender'].notnull()]

  first_name last_name   age Gender  pre_movie_score  post_movie_score
2      Stark      Mike  48.0      m              NaN               NaN

In [52]:
df[(df['pre_movie_score'].isnull()) | df['Gender'].isnull()]

  first_name last_name   age Gender  pre_movie_score  post_movie_score
1        NaN       NaN   NaN    NaN              NaN               NaN
2      Stark      Mike  48.0      m              NaN               NaN

**How to drop or replace null values?**

In [53]:
#count of missing values
df.isna().sum()

first_name          1
last_name           1
age                 1
Gender              1
pre_movie_score     2
post_movie_score    2
dtype: int64

In [54]:
df.isna().sum().sum() # total count of missing values

8

**Drop rows containing null values -**
0 :- index
1 :- columns

In [55]:
df

  first_name last_name   age Gender  pre_movie_score  post_movie_score
0       Root      Joss  36.0      m              8.0               9.0
1        NaN       NaN   NaN    NaN              NaN               NaN
2      Stark      Mike  48.0      m              NaN               NaN
3      Sofie    Miller  39.0      f              7.0               8.0
4       Emma       Roy  84.0      f              6.0               8.0

In [56]:
df1 = df.dropna(axis=0)

In [57]:
df1

  first_name last_name   age Gender  pre_movie_score  post_movie_score
0       Root      Joss  36.0      m              8.0               9.0
3      Sofie    Miller  39.0      f              7.0               8.0
4       Emma       Roy  84.0      f              6.0               8.0

In [58]:
df

  first_name last_name   age Gender  pre_movie_score  post_movie_score
0       Root      Joss  36.0      m              8.0               9.0
1        NaN       NaN   NaN    NaN              NaN               NaN
2      Stark      Mike  48.0      m              NaN               NaN
3      Sofie    Miller  39.0      f              7.0               8.0
4       Emma       Roy  84.0      f              6.0               8.0

In [59]:
# to avoid two sheets
#df.dropna(axis=0 ,inplace =True)

In [62]:
df1.isna().sum().sum()

0

**Drop columns containing Null values**

In [63]:
df2=df.dropna(axis=1)

In [64]:
df2

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

**threshint , optional**
it is helpful to maintain barrier that not to delete all columns

In [69]:
df4 = df.dropna(thresh=1) # default it considers axis =0 in padas

In [70]:
df4

  first_name last_name   age Gender  pre_movie_score  post_movie_score
0       Root      Joss  36.0      m              8.0               9.0
2      Stark      Mike  48.0      m              NaN               NaN
3      Sofie    Miller  39.0      f              7.0               8.0
4       Emma       Roy  84.0      f              6.0               8.0

In [71]:
df3 =  df.dropna(thresh=2)

In [72]:
df3

  first_name last_name   age Gender  pre_movie_score  post_movie_score
0       Root      Joss  36.0      m              8.0               9.0
2      Stark      Mike  48.0      m              NaN               NaN
3      Sofie    Miller  39.0      f              7.0               8.0
4       Emma       Roy  84.0      f              6.0               8.0

In [77]:
df5 = df.dropna(thresh = 4 , axis = 1)

In [78]:
df5

  first_name last_name   age Gender
0       Root      Joss  36.0      m
1        NaN       NaN   NaN    NaN
2      Stark      Mike  48.0      m
3      Sofie    Miller  39.0      f
4       Emma       Roy  84.0      f

**Fill null value**

In [79]:
df

  first_name last_name   age Gender  pre_movie_score  post_movie_score
0       Root      Joss  36.0      m              8.0               9.0
1        NaN       NaN   NaN    NaN              NaN               NaN
2      Stark      Mike  48.0      m              NaN               NaN
3      Sofie    Miller  39.0      f              7.0               8.0
4       Emma       Roy  84.0      f              6.0               8.0

In [80]:
df.fillna("NEW")

  first_name last_name   age Gender pre_movie_score post_movie_score
0       Root      Joss  36.0      m             8.0              9.0
1        NEW       NEW   NEW    NEW             NEW              NEW
2      Stark      Mike  48.0      m             NEW              NEW
3      Sofie    Miller  39.0      f             7.0              8.0
4       Emma       Roy  84.0      f             6.0              8.0

In [81]:
df['age']

0    36.0
1     NaN
2    48.0
3    39.0
4    84.0
Name: age, dtype: float64

In [83]:
df['age'].fillna(7)

0    36.0
1     7.0
2    48.0
3    39.0
4    84.0
Name: age, dtype: float64

In [84]:
df['first_name']

0     Root
1      NaN
2    Stark
3    Sofie
4     Emma
Name: first_name, dtype: object

In [88]:
df['first_name'] = df['first_name'].fillna("empty")

In [89]:
df

  first_name last_name   age Gender  pre_movie_score  post_movie_score
0       Root      Joss  36.0      m              8.0               9.0
1      empty       NaN   NaN    NaN              NaN               NaN
2      Stark      Mike  48.0      m              NaN               NaN
3      Sofie    Miller  39.0      f              7.0               8.0
4       Emma       Roy  84.0      f              6.0               8.0

**Data Imputation**

In [91]:
#find mean value of 'pre_movie_score' column
df['pre_movie_score'].mean()

7.0

In [92]:
df['pre_movie_score'] = df['pre_movie_score'].fillna(df['pre_movie_score'].mean())

In [93]:
df

  first_name last_name   age Gender  pre_movie_score  post_movie_score
0       Root      Joss  36.0      m              8.0               9.0
1      empty       NaN   NaN    NaN              7.0               NaN
2      Stark      Mike  48.0      m              7.0               NaN
3      Sofie    Miller  39.0      f              7.0               8.0
4       Emma       Roy  84.0      f              6.0               8.0

In [95]:
df['age'] = df['age'].fillna(int(df['age'].mean()))

In [96]:
df

  first_name last_name   age Gender  pre_movie_score  post_movie_score
0       Root      Joss  36.0      m              8.0               9.0
1      empty       NaN  51.0    NaN              7.0               NaN
2      Stark      Mike  48.0      m              7.0               NaN
3      Sofie    Miller  39.0      f              7.0               8.0
4       Emma       Roy  84.0      f              6.0               8.0

In [97]:
x = round(df['age'].mean())

In [98]:
x

52

In [103]:
df['age'] = df['age'].fillna(x)

In [104]:
df

  first_name last_name   age Gender  pre_movie_score  post_movie_score
0       Root      Joss  36.0      m              8.0               9.0
1      empty       NaN  51.0    NaN              7.0               NaN
2      Stark      Mike  48.0      m              7.0               NaN
3      Sofie    Miller  39.0      f              7.0               8.0
4       Emma       Roy  84.0      f              6.0               8.0

**Running second csv**

In [109]:
dz = pd.read_excel("/content/Data Cleaning_part1_dataset_Students_expenses.xlsx")

In [110]:
dz

   Expenses  Riya  Samual   Neeti  Shreya
0   January  8100  6200.0  9200.0  8150.0
1  February  9500  7500.0     NaN  7200.0
2     March  7300  6100.0  8800.0  8100.0
3     April  7800  7200.0  8900.0  7500.0
4       May  8500     NaN  9100.0  7800.0
5      June  9200  7100.0  8850.0     NaN

In [111]:
dz.mean()

<ipython-input-111-b9c5241c73b5>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  dz.mean()

Riya      8400.0
Samual    6820.0
Neeti     8970.0
Shreya    7750.0
dtype: float64

In [112]:
dz.fillna(dz.mean())

<ipython-input-112-82e594575398>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  dz.fillna(dz.mean())

   Expenses  Riya  Samual   Neeti  Shreya
0   January  8100  6200.0  9200.0  8150.0
1  February  9500  7500.0  8970.0  7200.0
2     March  7300  6100.0  8800.0  8100.0
3     April  7800  7200.0  8900.0  7500.0
4       May  8500  6820.0  9100.0  7800.0
5      June  9200  7100.0  8850.0  7750.0

In [113]:
#another method
dz.median()

<ipython-input-113-806537637dd9>:2: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  dz.median()

Riya      8300.0
Samual    7100.0
Neeti     8900.0
Shreya    7800.0
dtype: float64

In [114]:
df6 = dz.fillna(dz.median())

<ipython-input-114-a1983966435f>:1: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df6 = dz.fillna(dz.median())

In [115]:
df6

   Expenses  Riya  Samual   Neeti  Shreya
0   January  8100  6200.0  9200.0  8150.0
1  February  9500  7500.0  8900.0  7200.0
2     March  7300  6100.0  8800.0  8100.0
3     April  7800  7200.0  8900.0  7500.0
4       May  8500  7100.0  9100.0  7800.0
5      June  9200  7100.0  8850.0  7800.0